<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.scijava</groupId>
		<artifactId>pom-scijava</artifactId>
		<version>45.1.0</version>
		<relativePath />
	</parent>

	<groupId>sc.fiji</groupId>
	<artifactId>fiji-updater</artifactId>
	<version>3.0.0-SNAPSHOT</version>

	<name>Fiji Updater</name>
	<description>Keeps components of Fiji up-to-date.</description>
	<url>https://imagej.net/plugins/updater</url>
	<inceptionYear>2009</inceptionYear>
	<organization>
		<name>Fiji</name>
		<url>https://fiji.sc/</url>
	</organization>
	<licenses>
		<license>
			<name>Simplified BSD License</name>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<developers>
		<developer>
			<id>ctrueden</id>
			<name>Curtis Rueden</name>
			<url>https://imagej.net/people/ctrueden</url>
			<roles>
				<role>lead</role>
				<role>developer</role>
				<role>debugger</role>
				<role>reviewer</role>
				<role>support</role>
				<role>maintainer</role>
			</roles>
		</developer>
	</developers>
	<contributors>
		<contributor>
			<name>Johannes Schindelin</name>
			<url>https://imagej.net/people/dscho</url>
			<roles><role>founder</role></roles>
			<properties><id>dscho</id></properties>
		</contributor>
		<contributor>
			<name>Albert Cardona</name>
			<url>https://imagej.net/people/acardona</url>
			<properties><id>acardona</id></properties>
		</contributor>
		<contributor>
			<name>Mark Longair</name>
			<url>https://imagej.net/people/mhl</url>
			<properties><id>mhl</id></properties>
		</contributor>
		<contributor>
			<name>Mark Hiner</name>
			<url>https://imagej.net/people/hinerm</url>
			<properties><id>hinerm</id></properties>
		</contributor>
		<contributor>
			<name>Deborah Schmidt</name>
			<url>https://imagej.net/people/frauzufall</url>
			<properties><id>frauzufall</id></properties>
		</contributor>
		<contributor>
			<name>Matthias Arzt</name>
			<url>https://imagej.net/people/maarzt</url>
			<properties><id>maarzt</id></properties>
		</contributor>
		<contributor>
			<name>Nicolas Chiaruttini</name>
			<url>https://imagej.net/people/NicoKiaru</url>
			<properties><id>NicoKiaru</id></properties>
		</contributor>
		<contributor>
			<name>Jan Eglinger</name>
			<url>https://imagej.net/people/imagejan</url>
			<properties><id>imagejan</id></properties>
		</contributor>
		<contributor>
			<name>Tiago Ferreira</name>
			<url>https://imagej.net/people/tferr</url>
			<properties><id>tferr</id></properties>
		</contributor>
		<contributor>
			<name>Robert Haase</name>
			<url>https://imagej.net/people/haesleinhuepf</url>
			<properties><id>haesleinhuepf</id></properties>
		</contributor>
		<contributor>
			<name>Tobias Pietzsch</name>
			<url>https://imagej.net/people/tpietzsch</url>
			<properties><id>tpietzsch</id></properties>
		</contributor>
		<contributor>
			<name>Pradeep Rajasekhar</name>
			<url>https://imagej.net/people/pr4deepr</url>
			<properties><id>pr4deepr</id></properties>
		</contributor>
		<contributor>
			<name>Stephan Saalfeld</name>
			<url>https://imagej.net/people/axtimwalde</url>
			<properties><id>axtimwalde</id></properties>
		</contributor>
		<contributor>
			<name>Alison Walter</name>
			<url>https://imagej.net/people/awalter17</url>
			<properties><id>awalter17</id></properties>
		</contributor>
		<contributor>
			<name>Jarek Sacha</name>
			<url>https://imagej.net/people/jpsacha</url>
			<properties><id>jpsacha</id></properties>
		</contributor>
		<contributor>
			<name>Michael Heckel</name>
		</contributor>
		<contributor>
			<name>Yap Chin Kiet (Google Summer of Code 2009)</name>
		</contributor>
	</contributors>

	<mailingLists>
		<mailingList>
			<name>Image.sc Forum</name>
			<archive>https://forum.image.sc/tag/fiji</archive>
		</mailingList>
	</mailingLists>

	<scm>
		<connection>scm:git:https://github.com/fiji/fiji-updater</connection>
		<developerConnection>scm:git:git@github.com:fiji/fiji-updater</developerConnection>
		<tag>HEAD</tag>
		<url>https://github.com/fiji/fiji-updater</url>
	</scm>
	<issueManagement>
		<system>GitHub Issues</system>
		<url>https://github.com/fiji/fiji-updater/issues</url>
	</issueManagement>
	<ciManagement>
		<system>GitHub Actions</system>
		<url>https://github.com/fiji/fiji-updater/actions</url>
	</ciManagement>

	<properties>
		<package-name>sc.fiji.updater</package-name>
		<main-class>sc.fiji.updater.CommandLine</main-class>

		<license.licenseName>bsd_2</license.licenseName>
		<license.copyrightOwners>Fiji developers.</license.copyrightOwners>
		<license.projectName>Fiji software for multidimensional image processing and analysis.</license.projectName>

		<!-- NB: Deploy releases to the SciJava Maven repository. -->
		<releaseProfiles>sign,deploy-to-scijava</releaseProfiles>

		<app-launcher.version>2.3.1</app-launcher.version>
	</properties>

	<repositories>
		<repository>
			<id>scijava.public</id>
			<url>https://maven.scijava.org/content/groups/public</url>
		</repository>
	</repositories>

	<dependencies>
		<!-- SciJava dependencies -->
		<dependency>
			<groupId>org.scijava</groupId>
			<artifactId>app-launcher</artifactId>
			<version>${app-launcher.version}</version>
		</dependency>
		<dependency>
			<groupId>org.scijava</groupId>
			<artifactId>scijava-common</artifactId>
		</dependency>

		<!-- Test scope dependencies -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.scijava</groupId>
			<artifactId>scijava-common</artifactId>
			<classifier>tests</classifier>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
